### ISSUE TITLE
cabal-helper is not compatible with "no-reinstall cabal"

### ISSUE THREAD

**Issue by dgpratt** [DanielG/cabal-helper#14]
In its current form, ["no-reinstall Cabal"](http://blog.ezyang.com/2015/08/help-us-beta-test-no-reinstall-cabal/) does not export inplacePackageId, which is used by cabal-helper [here](https://github.com/DanielG/cabal-helper/blob/0a0090bbb8d1fa8ffe42cc7a09fa8f2fd0350109/CabalHelper/Main.hs#L383).

**Comment by DanielG** [comment]
Did this ever get merged into Cabal master? Since everything seems to be working with that otherwise I'll probably fix that when it gets merged.
