### ISSUE TITLE
bump upper bounds of Cabal to 1.23 ?

### ISSUE THREAD

**Issue by robstewart57** [DanielG/cabal-helper#16]
Is there a reason why the dependencies of the cabal-helper library, the cabal-helper-wrapper executable and the spec testsuite cannot be bumped to 1.23? I.e. to include rather than disallow 1.23 as an upper bound.

**Comment by DanielG** [comment]
Well the uneven versions are the ones in git, right? I don't really test with those so it's probably best not to bump the version. I'll raise the bound when a new version is released.

**Comment by robstewart57** [comment]
Ah, I see. And there's me compiling ghc-mod with cabal-install from cabal's git repo. Is this therefore not advised? I.e. always just use cabal-install as is released on hackage?

**Comment by DanielG** [comment]
It's not advised (i.e. supported by me) no. But if you want to do that sort of thing and fling patches my way when stuff breaks or something we can always add a `dev` flag that relaxes the upper bounds.

**Comment by DanielG** [comment]
Done + support for the current Cabal-1.23 that shipped with GHC 8.0.0-rc2
