### ISSUE TITLE
Test suite has undeclared dependency on 'cabal-install'

### ISSUE THREAD

**Issue by peti** [DanielG/cabal-helper#17]
Citing from http://hydra.cryp.to/build/1533267/nixlog/1/raw:

```
Running 1 test suites...
Test suite spec: RUNNING...
spec: cabal: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite spec: FAIL
```

Nix builds include only those packages that the Cabal declares as a required build input, and since there's no `build-tools: cabal` attribute associated with the test suite, no `cabal` binary is available in the chroot environment that compiles this package.

**Comment by DanielG** [comment]
Is that a new feature? I don't remember `cabal` being one of the build-tools you could specify in older versions of Cabal. Problem is we have to support Cabal going back to version 1.16.

**Comment by DanielG** [comment]
Yeah, just what I thought: https://travis-ci.org/DanielG/cabal-helper/jobs/101560593#L208

**Comment by peti** [comment]
The Cabal library has no predefined parser for `cabal`. You'll have to declare it in `Setup.hs`, i.e. like this:

``` Haskell
import Distribution.Simple
import Distribution.Simple.Program

main :: IO ()
main = defaultMainWithHooks simpleUserHooks
       { hookedPrograms = [ simpleProgram "cabal" ]
       }
```

The http://hackage.haskell.org/package/zip-archive package might be useful as an example. It uses the same approach to declare a dependency on the `zip` system utility.

**Comment by DanielG** [comment]
Okay got it working with that. Should be fixed in master now. I'll do another release some time before releasing ghc-mod 5.5. Thanks.

**Comment by peti** [comment]
Very cool, thank you!
