### ISSUE TITLE
cabal-helper-0.3.4.0 test suite shouldn't access $HOME

### ISSUE THREAD

**Issue by peti** [DanielG/cabal-helper#2]
The test suite fails in NixOS, http://hydra.cryp.to/build/805079/log/raw, because builds do not have `$HOME` configured. It's probably a bad idea to rely on that path to accessible for a test suite run. Instead, I'd recommend using `$TMPDIR` or something like that.

**Comment by DanielG** [comment]
Gah. That's probably Cabal creating $HOME not me. How did you work around that for cabal-install?

**Comment by DanielG** [comment]
Oh NVM cabal-helper needs $HOME to store it's build outputs, forgot about that. I don't really see a way around that though.

**Comment by peti** [comment]
Well, if there is no way to work around the dependency on `$HOME` for the time being, then I'll just remove the package from the NixOS distribution to mitigate the failing build in our CI system.

**Comment by DanielG** [comment]
Can't you just override $HOME to be /tmp or something? It's not like the test suite outputs have to go into the distribution.

**Comment by peti** [comment]
Well, we can set `$HOME` to some temporary location during the build. Doing so feels like a kludge, though. A test suite really shouldn't store data in `$HOME`. Maybe the test suite could set `$HOME` to `$TMPDIR` itself?
