### ISSUE TITLE
Error checking file in Spacemacs Haskell Mode

### ISSUE THREAD

**Issue by aljce** [DanielG/cabal-helper#20]
When attempting to load a file in spacemacs haskell mode I get the following error [ http://lpaste.net/157693](url)

The thing is the file they are refrencing doesnt exist on my computer.

**Comment by DanielG** [comment]
Hmm this usually only happens when something goes wrong during installation, do you have the latest version of stack?

**Comment by aljce** [comment]
Very odd updated stack and it worked after some messing arround with file permissions on ~/.stack and my respective ".stack-work"s. Perhaps this issue can be closed.

**Comment by DanielG** [comment]
Well do shout if the issue creeps up again :)
