### ISSUE TITLE
Reintroduced restrictive upper bounds

### ISSUE THREAD

**Issue by snoyberg** [DanielG/cabal-helper#25]
process-1.4.2.0 is out of bounds for:
- [ ] cabal-helper-0.7.1.0 (>=1.1.0.1 && < 1.3). Daniel Gröber dxld@darkboxed.org @DanielG. @DanielG

template-haskell-2.11.0.0 is out of bounds for:
- [ ] cabal-helper-0.7.1.0 (>=2.7.0.0 && < 2.11). Daniel Gröber dxld@darkboxed.org @DanielG. @DanielG

**Comment by DanielG** [comment]
Should be fixed by revision 2.
