### ISSUE TITLE
Release 0.7.3.0 not in GitHub

### ISSUE THREAD

**Issue by 3noch** [DanielG/cabal-helper#27]
Hackage has a release that's not on GitHub.

**Comment by DanielG** [comment]
Whoops, my bad. I was playing with GitLab/GitLabCI for this release and forgot to sync those changes back here. Done now though. (https://gitlab.com/dxld/cabal-helper/)

**Comment by 3noch** [comment]
Thanks. Neat. Hope GitLab works out for you!
