### ISSUE TITLE
Failure to locate binary while installing with Stack

### ISSUE THREAD

**Issue by dniku** [DanielG/cabal-helper#28]
When I install `cabal-helper` with Stack, I get this error:

    Couldn't find executable cabal-helper-wrapper in directory <project-directory>/.stack-work/install/x86_64-linux/lts-8.5/8.0.2/bin/

However, the binary is there, under `.stack-work/install/x86_64-linux/lts-8.5/8.0.2/libexec/x86_64-linux-ghc-8.0.2/cabal-helper-0.7.3.0/cabal-helper-wrapper`, so if I issue

    cp .stack-work/install/x86_64-linux/lts-8.5/8.0.2/libexec/x86_64-linux-ghc-8.0.2/cabal-helper-0.7.3.0/cabal-helper-wrapper .stack-work/install/x86_64-linux/lts-8.5/8.0.2/bin/

and run `stack install cabal-helper` again, I get

```
Copying from <project-directory>/.stack-work/install/x86_64-linux/lts-8.5/8.0.2/bin/cabal-helper-wrapper to /home/ser/.local/bin/cabal-helper-wrapper

Copied executables to /home/ser/.local/bin/:
- cabal-helper-wrapper
```

I'm not sure whether this is an issue with Stack or `cabal-helper`, but `cabal-helper` is the only package I've seen that exhibits this behavior.

I execute all commands from the directory where https://github.com/input-output-hk/cardano-sl is cloned. Its latest `.cabal` file is [here](https://github.com/input-output-hk/cardano-sl/blob/b1df2ff43ccab2c266bb94dbe8bae395b3667863/cardano-sl.cabal). My [`stack --version`](https://gist.github.com/Pastafarianist/0d543e6afa78445ff90a81e6e177efd2).

See also the [mirror](https://github.com/commercialhaskell/stack/issues/3202) of this issue in the Stack repository.

**Comment by DanielG** [comment]
I've implemented a generic mechanism for having Cabal install executables in `$libexec` and `#ifdef`ed out the hax in our Setup.hs for Cabal>2.0. See https://github.com/haskell/cabal/pull/4501. Lets hope Stack handles that better.
