### ISSUE TITLE
Can't build on Windows due to unix dependency

### ISSUE THREAD

**Issue by LukaHorvat** [DanielG/cabal-helper#35]
I'm building the current HEAD and it fails because you can't build unix on Windows. Is there a workaround there?

**Comment by Anrock** [comment]
@LukaHorvat there is no way to build unix on Windows, so the only workaround to compile cabal-helper is to clone repo and revert 4b357a where unix package was introduced.
@DanielG i really hope this commit will be reverted - HIE is depending on cabal-helper and small refactoring isn't worth losing platform support.

**Comment by DanielG** [comment]
I'm happy to accept patches. Conditionally removing the `unix` dependency on windows should be pretty straight forward. The only use site is here: https://github.com/DanielG/cabal-helper/blob/master/src/CabalHelper/Compiletime/Data.hs#L59

**Comment by LukaHorvat** [comment]
Could it be as simple as switching to `unix-compat`? It does have `epochTime`. I'm unsure about that ENV variable though.

**Comment by Anrock** [comment]
Unfortunetaly unix-compat doesn't wrap env. I'll try to make it conditional, however, being a haskell noob, i have no idea how long will it take.

**Comment by Anrock** [comment]
Looks like i managed to get it working using `unix-compat`, expanding `CabalHelper.Compiletime.Compat.Environment` with `setEnv` and bumping `base` to `4.7` for win builds.
Probably will send PR tomorrow.

**Comment by Anrock** [comment]
@DanielG is there a way to run tests using stack?

**Comment by DanielG** [comment]
`$ stack test` I assume but the tests on the master branch really only try to compile the runtime components against all possible Cabal versions. As long as you enable the `dev` flag when building to also compile the runtime stuff you should be good.

**Comment by Anrock** [comment]
@DanielG `stack test` fails every test with
`Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times)`
Looks like `--no-ghc-package-path` should help, however `stack test` doesn't support it.

**Comment by Anrock** [comment]
@DanielG well at least it builds, can you check tests are ok? #36

**Comment by DanielG** [comment]
Should be fixed on master.
