### ISSUE TITLE
cabal-helper fails on ghc-mod commands for project

### ISSUE THREAD

**Issue by mvoidex** [DanielG/cabal-helper#4]
I'm not sure when it was broken, but ghc-mod now fails when executed within project directory.
`box` is newly created project with `cabal init`, configured and installed, and no sandbox there

```
PS D:\users\voidex\Documents\Projects\box> ghc-mod check .\src\Test.hs
cabal-helper-wrapper.exe: C:\Users\Alexandr\AppData\Local\Temp\cabal-helper7856\CabalHelper\Main.hs: commitBuffer: invalid argument (invalid character)
ghc-mod.exe: readCreateProcess: C:\Users\Alexandr\AppData\Roaming\cabal\cabal_0P5q9UpHEkV3g6HCMgHTaZ\cabal-helper-wrapper.exe "D:\\users\\voidex\\Documents\\Projects\\box\\dist" "entrypoints" "source-dirs" "ghc-options" "ghc-src-options" "ghc-pkg-options" "ghc-merged-pkg-options" "ghc-lang-options" "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" (exit 1): failed
```

**Comment by DanielG** [comment]
hmrpf

Compile cabal-helper with profiling enabled and run it with `+RTS -xc` and the rest of the command line mentioned in the last line of your snippet. This seems to be some sort of utf8/locale/binary-data-where-it-shouldn't-be related issue.

**Comment by DanielG** [comment]
Looks like I can reproduce this in a clean linux container too; `export LC_ALL="C.UTF-8"` fixes it there.  I could swear I already fixed a locale related issue ...

**Comment by DanielG** [comment]
Ah https://github.com/DanielG/cabal-helper/commit/f69f35bc4af49b3a25ed6407375c03f5b7569432

**Comment by DanielG** [comment]
@mvoidex try the above commit please

**Comment by mvoidex** [comment]
@DanielG, commit fixes the issue, thanks
