### ISSUE TITLE
Add cabal to build-tool-depends

### ISSUE THREAD

**Issue by nponeccop** [DanielG/cabal-helper#40]
@DanielG wrote in https://github.com/haskell/haskell-ide-engine/issues/372 :

The dependency on the `cabal` executable is declared in [Setup.hs](https://github.com/DanielG/cabal-helper/blob/master/Setup.hs#L38) but that only applies to `Cabal < 2` so I guess we should probably add cabal to `build-tool-depends` actually.

**Comment by DanielG** [comment]
We have `build-tool-depends:  cabal-install:cabal` in the (hopefully) appropriate places now: https://github.com/DanielG/cabal-helper/blob/master/cabal-helper.cabal#L144. This got released in cabal-helper-0.8.0.0.
