### ISSUE TITLE
Can not build 0.8.0.0 with stack 

### ISSUE THREAD

**Issue by ShrykeWindgrace** [DanielG/cabal-helper#41]
When I run `stack init --solver`, I get 
```
Using resolver: lts-10.3
Using compiler: ghc-8.2.2
Asking cabal to calculate a build plan...
Trying with packages from lts-10.3 as hard constraints...
Could not parse cabal-install errors:

>>>> Cabal errors begin
cabal.EXE:
E:\nosave\Projects\Haskell\StackPackages\cabal-helper-0.8.0.0\tests\bkpregex\bkpregex.cabal:
This package requires at least Cabal version 2.0
<<<< Cabal errors end

CallStack (from HasCallStack):
  error, called at src/Stack\Solver.hs:130:25 in stack-1.6.3-F6YVX3qh2MsHZufmhdWM8J:Stack.Solver
```
The problem is present on both ubuntu and win10 with stack-1.6.3

What is the correct approach to build cabal-helper here?

**Comment by DanielG** [comment]
Well the correct approach is to use `cabal` :)

The problem is we have a bunch of cabal files in the `tests/` directory that are just test fixtures and not part of a multi package project or anything. `stack init --ignore-subdirs` seems to work though.

**Comment by ShrykeWindgrace** [comment]
It worked indeed. Thank you!
