### ISSUE TITLE
Tag 0.8.0.0 release in git (v0.8.0.0)

### ISSUE THREAD

**Issue by mbbx6spp** [DanielG/cabal-helper#42]
I don't see a tag for the 0.8.0.0 release yet which appears to be uploaded to Hackage already[1].

```
$ git ls-remote git@github.com:DanielG/cabal-helper.git v0.7.2.0 | wc -l
1

$ git ls-remote git@github.com:DanielG/cabal-helper.git v0.8.0.0 | wc -l
0
```

[1]: https://hackage.haskell.org/package/cabal-helper-0.8.0.0

**Comment by DanielG** [comment]
I do always forget to push the tags, sorry!
