### ISSUE TITLE
Fix suggestion for `-i` flags and the `cabal-preprocessors` test

### ISSUE THREAD

**Issue by ulidtko** [DanielG/cabal-helper#47]
Hi @DanielG 

I've been struggling to setup `ghc-mod` on Arch Linux with dynamic-only GHC 8.2 (Cabal-2.0.1.0, cabal-install-2.0.0.1, no stackage) for a while now. There's only a partial success, and I've identified a couple of issues; one of which seems to have the root cause contained within these lines:

https://github.com/DanielG/cabal-helper/blob/b81f78ab5008506ebefa75d6d8aa512e4e7a378e/src/CabalHelper/Runtime/Main.hs#L500-L506

The `#if` looks wrong to me; perhaps it should be inverted. Was the real intention to use `componentOutDir` on Cabal >= 2.0 (and `componentBuildDir` otherwise) perhaps?.. 

I base the "looks wrong" conclusion on a single assumption, that `cabal-helper ... ghc-options` should output about the same cmdline as `cabal repl --verbose`. On current `master`, this is not the case.

-----
Let's see the `dist` structure of a trivial package:

```
dist
├── build
│   └── foo-pkg
│       ├── autogen
│       │   ├── cabal_macros.h
│       │   └── Paths_foo_pkg.hs
│       └── foo-pkg-tmp
├── cabal-config-flags
├── package.conf.inplace
│   ├── package.cache
│   └── package.cache.lock
├── setup-config
├── setup-config.ghc-mod.cabal-components
├── setup-config.ghc-mod.package-options
└── setup-config.ghc-mod.resolved-components
```

`foo-pkg-tmp` is the `componentOutDir` if I'm not mistaken. `cabal repl` passes that to `ghc`:

<pre>
[foo-pkg] cabal repl --verbose
Using internal setup method with build-type Simple and args:
["repl","--verbose=2","--builddir=dist"]
/usr/bin/ghc-pkg init dist/package.conf.inplace
creating dist/build/foo-pkg
creating dist/build/foo-pkg/autogen
creating dist/build/foo-pkg/autogen
Preprocessing executable 'foo-pkg' for foo-pkg-0.1.0.0..
creating dist/build/foo-pkg
creating dist/build/foo-pkg/foo-pkg-tmp
/usr/bin/ghc --interactive
    -fbuilding-cabal-package
    -O0
    <strong>-outputdir dist/build/foo-pkg/foo-pkg-tmp</strong>
    <strong>-odir dist/build/foo-pkg/foo-pkg-tmp</strong>
    <strong>-hidir dist/build/foo-pkg/foo-pkg-tmp</strong>
    <strong>-stubdir dist/build/foo-pkg/foo-pkg-tmp</strong>
    -i
    <strong>-idist/build/foo-pkg/foo-pkg-tmp</strong>
    -i.
    -idist/build/foo-pkg/autogen
    -idist/build/global-autogen
    -Idist/build/foo-pkg/autogen
    -Idist/build/global-autogen
    -Idist/build/foo-pkg/foo-pkg-tmp
    -optP-include
    -optPdist/build/foo-pkg/autogen/cabal_macros.h
    -hide-all-packages
    -Wmissing-home-modules
    -package-db dist/package.conf.inplace
    -package-id base-4.10.1.0
    -package-id comonad-5.0.3-1wQLfIXhDc15HcgpkWgfSP
    -XHaskell2010 ./Main.hs -dynamic
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ulidtko/.config/dotfiles/HOME/ghci
[1 of 1] Compiling Main             ( Main.hs, interpreted )
Ok, one module loaded.
</pre>
(I've added some layout for legibility.)

But cabal-helper in `b81f78a` does something different (due to the lines I quoted above):
<pre>
[foo-pkg] ghc-mod -vvvvv check Main.hs
info: Found Cabal project at: /home/ulidtko/src/ghc-mod/test/foo-pkg
info: Using Cabal project at: /home/ulidtko/src/ghc-mod/test/foo-pkg
DEBUG: setup configuration is out of date
DEBUG: reconfiguring Cabal project
[1 of 4] Compiling CabalHelper.Shared.Common ( /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/Common.hs, /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/Common.o )
[2 of 4] Compiling CabalHelper.Shared.InterfaceTypes ( /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/InterfaceTypes.hs, /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/InterfaceTypes.o )
[3 of 4] Compiling CabalHelper.Shared.Sandbox ( /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/Sandbox.hs, /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Shared/Sandbox.o )
[4 of 4] Compiling Main             ( /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/CabalHelper/Runtime/Main.hs, /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0.build/Main.o )
Linking /home/ulidtko/.cache/cabal-helper/cabal-helper0.8.0.2-Cabal2.0.1.0 ...
DEBUG: regenerating cache: /home/ulidtko/src/ghc-mod/test/foo-pkg/dist/setup-config.ghc-mod.cabal-components (cache missing or unreadable)
DEBUG: writing memory cache: /home/ulidtko/src/ghc-mod/test/foo-pkg/dist/setup-config.ghc-mod.cabal-components
DEBUG: resolveEntrypoint:
       ["-i","-idist/build/foo-pkg","-i.","-idist/build/foo-pkg/autogen","-idist/build/global-autogen","-Idist/build/foo-pkg/autogen","-Idist/build/global-autogen","-Idist/build/foo-pkg","-optP-include","-optPdist/build/foo-pkg/autogen/cabal_macros.h"]
DEBUG: resolveEntrypoint: []
DEBUG: making sure autogen files exist
DEBUG: autogen files out of sync
DEBUG: writing Cabal autogen files
DEBUG: resolvedComponentsCache: files changed: none
DEBUG: resolveGmComponent:
       ["-optP-include","-optPdist/build/autogen/cabal_macros.h"]
DEBUG: resolveGmComponent:
       ["-i","-idist/build/foo-pkg","-i.","-idist/build/foo-pkg/autogen","-idist/build/global-autogen","-Idist/build/foo-pkg/autogen","-Idist/build/global-autogen","-Idist/build/foo-pkg","-optP-include","-optPdist/build/foo-pkg/autogen/cabal_macros.h","-XHaskell2010","-optP-include","-optPdist/build/autogen/cabal_macros.h"]
DEBUG: regenerating cache: dist/setup-config.ghc-mod.resolved-components (cache missing or unreadable)
DEBUG: writing memory cache: dist/setup-config.ghc-mod.resolved-components
VOMIT: Initializing GHC session with following options:
    "-fbuilding-cabal-package"
    "-O"
    <strong>"-outputdir" "dist/build/foo-pkg"</strong>
    <strong>"-odir" "dist/build/foo-pkg"</strong>
    <strong>"-hidir" "dist/build/foo-pkg"</strong>
    <strong>"-stubdir" "dist/build/foo-pkg"</strong>
    "-i"
    <strong>"-idist/build/foo-pkg"</strong>
    "-i."
    "-idist/build/foo-pkg/autogen"
    "-idist/build/global-autogen"
    "-Idist/build/foo-pkg/autogen"
    "-Idist/build/global-autogen"
    "-Idist/build/foo-pkg"
    "-optP-include"
    "-optPdist/build/foo-pkg/autogen/cabal_macros.h"
    "-hide-all-packages"
    "-Wmissing-home-modules"
    "-package-id" "base-4.10.1.0"
    "-package-id" "comonad-5.0.3-1wQLfIXhDc15HcgpkWgfSP"
    "-XHaskell2010" "-dynamic" "-Wno-missing-home-modules" "-O0"
</pre>

*I think* this supposedly ought to match the `cabal repl` cmdline.

-----
Anyhow, this quick-n-dirty patch:

```diff
-#if CH_MIN_VERSION_Cabal(2,0,0)
-           outdir = componentBuildDir lbi clbi
-#else
            outdir = componentOutDir lbi c
-#endif
```

-- fixes the cmdline; it also **fixes the `cabal-preprocessors` spec test** on Cabal 2.0. I'm able to replicate locally [the test failure][CI] on `master`; applying *quick-n-dirty* fixes that test.

For completeness, I can see that @alanz fixes the `cabal-preprocessors` test in #46, although in a different way. I think that fix will work, but it will also mask the real bug (which is the incorrect version check for componentOutDir/componentBuildDir) which causes the issue in the first place.

I'm not sending this as a PR just yet -- simply because it'd be way too hard, and too irrelevant for my real goal, to test this under Cabal 1.24.

Am intrigued to hear if this is indeed a real catch (or if I'm totally off the track here). In the positive case, I'll gladly save you a dozen keystrokes by making a pull request.

[CI]: https://gitlab.com/dxld/ghc-mod/-/jobs/52021484

**Comment by alanz** [comment]
Sounds interesting.

That #if came in because the example I was looking at at the time seemed to need it.  But please make a PR, I would love to see progress on this.

**Comment by ulidtko** [comment]
Ok. Is there any way to trigger CI on this for the older ghc+cabal combos?

**Comment by DanielG** [comment]
I added you as a collaborator, just push the your PR branch into this repo and GitLab will mirror it and trigger a CI build within the hour (or when I manually trigger the sync).

**Comment by ulidtko** [comment]
Cool, thank you! Will watch GitLab while I try to sort out the other `-dynamic` issues over here.

**Comment by DanielG** [comment]
Looks like the build is erroring now. I meant you should push the PR into another branch, not master, and merge when ready FYI. I updated the branch protections to require PR review and CI to be green. Just push your fixes for the build errors into a new branch and PR that like usual.

**Comment by ulidtko** [comment]
Closing this, let's continue in PR #49.
