### ISSUE TITLE
Restrictive upper bounds on pretty-show and temporary

### ISSUE THREAD

**Issue by ElvishJerricco** [DanielG/cabal-helper#59]
These bounds are a little too strict: `pretty-show >=1.8.1 && <1.9, temporary >=1.2.1 && <1.3`. Pretty sure they can be bumped.

**Comment by ulidtko** [comment]
This is pretty common situation in the Haskell package ecosystem.

You can try `cabal install --allow-newer`.

**Comment by ElvishJerricco** [comment]
Yep, but a revision or something on Hackage would be nice.

**Comment by DanielG** [comment]
The latest `pretty-show` version is 1.8.2, which is in bounds, so I don't see your point?

I'd be happy to bump `temporary` to 1.3 though if you can confirm that the build succeeds with it.

**Comment by ElvishJerricco** [comment]
@DanielG Ah, my bad. I'm building in nixpkgs, and `pretty-show` is actually *beneath* that version bound. Looks like it builds with 1.7. Should that be relaxed?

**Comment by DanielG** [comment]
Sure. Did you test with temporary 1.3 too?

**Comment by ElvishJerricco** [comment]
I tested that it *builds*, but haven't actually run the test suite.

**Comment by langston-barrett** [comment]
In case anyone else finds this issue via trying to build a package that depends on this one with Nix, here's how to do it:
```nix
{ pkgsOld   ? import <nixpkgs> { }
, compiler  ? "ghc844"
}:

let
  config = {
    packageOverrides = pkgs: rec {
      haskellPackages =
        # builtins.trace (builtins.concatStringsSep "\n" (builtins.attrNames pkgs.haskell.packages))
        pkgs.haskell.packages."${compiler}".override {
        overrides = haskellPackagesNew: haskellPackagesOld: {
          cabal-helper = pkgs.haskell.lib.doJailbreak haskellPackagesOld.cabal-helper;
        };
      };
    };
  };
  pkgs = import <nixpkgs> { inherit config; };
in with pkgs; haskellPackages.callPackage ./default.nix { }
```
