### ISSUE TITLE
Cabal helper ties to install 2.4.0.1 even if 2.4.1.0 is installed

### ISSUE THREAD

**Issue by majkrzak** [DanielG/cabal-helper#73]
I'm fighting with vs-code for Haskell setup. Between plenty of issues I've found that cabal-helper is installing `2.4.0.1` cabal even if `cabal-static 2.4.1.0-1` is installed on my Arch

**Comment by DanielG** [comment]
I mean, look at those version numbers they are not the same. So what would you expect it to do? Honestly I don't have much to go on here, not even a cabal-helper version number. Mind being a bit more detailed.

If I'm reading https://aur.archlinux.org/packages/cabal-static/ right it seems to me that this is the `cabal` executable, not the `Cabal` library. Those version numbers are usually distinct. `cabal --version` will tell you the `lib:Cabal` version it's using internally.

You always have the option of just installing the relevant lib:Cabal version with your system package manager or using `cabal` or even `stack` (only if you use stack projects) but the versions really have to match exactly.

**Comment by majkrzak** [comment]
Now I got it, sorry.

**Comment by DanielG** [comment]
I'm closing this then.
