### ISSUE TITLE
Change license to Apache2

### ISSUE THREAD

**Issue by DanielG** [DanielG/cabal-helper#76]
Hey guys. I would like to change cabal-helper's license from GPLv3+ to Apache2 to allow ghcide (formerly hie-core) to use it. @bubba, @wz1000, @alanz 

If you don't have any objections please just say you agree below so we have this on public record, thanks.

**Comment by alanz** [comment]
Agree 😃

**Comment by lukel97** [comment]
Agree

**Comment by ulidtko** [comment]
Agreed as well.

ср, 18 вер. 2019, 01:45 користувач Luke Lau <notifications@github.com> пише:

**Comment by wz1000** [comment]
Agree
