### ISSUE TITLE
Error compiling cabal-helper at runtime using stack-2.1.3 due to two simultaneous cabal versions 

### ISSUE THREAD

**Issue by jneira** [DanielG/cabal-helper#78]
* When trying to run the haskell-ide-engine unit test suite in appveyor i've got several warnings and errors cause it is compiled against two versions of cabal but i think i got this error running the test suite in azure as well.
* I can't reproduce it in my local windows machine.
* Appveyor build: https://ci.appveyor.com/project/jneira/haskell-ide-engine/builds/27821597?fullLog=true
* There are several warnings like:
```
In file included from <command-line>:10:0: error: 
C:/Users/appveyor/AppData/Local/Temp/ghc2460_0/ghc_2.h:7:0: warning: "VERSION_Cabal" redefined
 #define VERSION_Cabal "2.4.1.0"
```
* And errors:
```
C:\\Users\appveyor\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\Common.hs:42:1: error:
    Ambiguous module name `Distribution.PackageDescription.Parsec':
      it was found in multiple packages: Cabal-2.4.0.1 Cabal-2.4.1.0
   |
42 | import qualified Distribution.PackageDescription.Parsec as P
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Thanks in advance!

**Comment by jneira** [comment]
Builds in azure ci with the same errors: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=209

**Comment by jneira** [comment]
It seems to me that `cabal-helper` is being compiled against the builting `Cabal` lib of ghc
With `ghc-8.2.2`, from azure build `MacOs_Stack stack-8.2.2`:
```
haskell-ide-engine> /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ghc49753_0/ghc_2.h:7:9: error:
haskell-ide-engine>      warning: 'VERSION_Cabal' macro redefined [-Wmacro-redefined]
haskell-ide-engine>   |
haskell-ide-engine> 7 | #define VERSION_Cabal "2.0.1.1"
haskell-ide-engine>   |         ^
haskell-ide-engine> #define VERSION_Cabal "2.0.1.1"
haskell-ide-engine>         ^
```

Otoh the builds for `ghc-8.4.*` (with `Cabal-2.2.0.1`) and  `ghc-8.6.1` (with `Cabal-2.4.0.1`) haven't those errors. But `ghc-8.6.2` with the same Cabal version fails. So it seems in those versions the two sources of cabal versions match.

**Comment by DanielG** [comment]
You could try turning on debugging by setting `CABAL_HELPER_DEBUG=1` in the environment, that should give you the GHC command line that's being run there.

FYI you're running HIE's fork of cabal-helper which by now is over a year old. I don't really provide support for that but if you get me the GHC command line we should be able to see what's wrong.

**Comment by jneira** [comment]
@DanielG thanks! i'll debug it anyway if you dont mind although the incoming hie-bios branch doesnt have those errors.

**Comment by jneira** [comment]
Ok, after removing the existent compiled cabal-helper at runtime i have reproduced the error in local. It is triggered by stack builds:
* log of hie test suite with stack:
```
Building all executables for `testdata' once. After a successful build of all of them, only specified executables will be rebuilt.
testdata> configure (exe)
Configuring testdata-0.1.0.0...
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe --numeric-version
=> 8.6.5

D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe list --simple-output Cabal
=> Cabal-2.4.0.1 Cabal-2.4.1.0

using helper compiled with Cabal from user/global package-db
helper exe does not exist, compiling C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1
compSrcDir: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build
compOutDir: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build
compExePath: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe -outputdir 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -o 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1' -optP-DCABAL_HELPER=1 '-optP-DCH_MIN_VERSION_Cabal(major1,major2,minor)=(  (major1)  < 2 || (major1) == 2 && (major2)  < 4 || (major1) == 2 && (major2) == 4 && (minor) <= 0)' -i '-iC:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -hide-all-packages -package base -package containers -package directory -package filepath -package process -package bytestring -package ghc-prim -package Cabal-2.4.0.1 -w --make 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Runtime\Main.hs'
Loaded package environment from D:\\msys64\tmp\stack2368\test-ghc-env
Loaded package environment from D:\\msys64\tmp\stack2368\test-ghc-env

In file included from <command-line>:10:0: error:
C:/TEMP/ghc10312_0/ghc_2.h:7:0: warning: "VERSION_Cabal" redefined
 #define VERSION_Cabal "2.4.1.0"

C:/TEMP/ghc10312_0/ghc_2.h:1:0: note: this is the location of the previous definition
 #define VERSION_Cabal "2.4.0.1"
```

* check ghc databases:

```
> "D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe" list --simple-output Cabal
Cabal-2.4.0.1
```

* Running it with cabal (after informing the `cabal_helper_libexecdir` env var, cause i am using `v2-build` with a custom `store-dir` in `D:\csd` and `cabal-helper-wrapper.exe` is there (in `D:\csd\cabal-helper-{hash}\bin`) and no within `dist-newstyle` nor `%APPDATA%\cabal\....`, ignoring my `libexecdir` custom cabal config value)

```
Building all executables for `testdata' once. After a successful build of all of them, only specified executables will be rebuilt.
testdata> configure (exe)
Configuring testdata-0.1.0.0...
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe --numeric-version
=> 8.6.5

D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe list --simple-output Cabal
=> Cabal-2.4.0.1

using helper compiled with Cabal from user/global package-db
helper exe does not exist, compiling C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1
compSrcDir: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build
compOutDir: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build
compExePath: C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe -outputdir 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -o 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1' -optP-DCABAL_HELPER=1 '-optP-DCH_MIN_VERSION_Cabal(major1,major2,minor)=(  (major1)  < 2 || (major1) == 2 && (major2)  < 4 || (major1) == 2 && (major2) == 4 && (minor) <= 0)' -i '-iC:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -hide-all-packages -package base -package containers -package directory -package filepath -package process -package bytestring -package ghc-prim -package Cabal-2.4.0.1 -w --make 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Runtime\Main.hs'
....
Linking C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal
2.4.0.1 ...
```

So, weirdly enough, running `ghc-pkg.exe list --simple-output Cabal` inside the stack execution gives another value that running it directly or within cabal :open_mouth: 

Sorry for bother with problems with a deprecated version, feel free to ignore this and to close the issue

**Comment by jneira** [comment]
> So, weirdly enough, running ghc-pkg.exe list --simple-output Cabal inside the stack execution gives another value that running it directly or within cabal

```
D:\ws\haskell\haskell-ide-engine>stack exec ghc-pkg -- list Cabal
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\lib\package.conf.d
    Cabal-2.4.0.1

D:\sr\snapshots\f64ff031\pkgdb
    Cabal-2.4.1.0

D:\ws\haskell\haskell-ide-engine\.stack-work\install\69d95b10\pkgdb
    (no packages)
```

**Comment by jneira** [comment]
So the workaround could be:
```
> distdir=$(stack path --dist-dir)
> stack exec cabal-helper-wrapper -- v1-style $distdir print-exe
```
to force the compiling of cabal-helper at runtime with a "correct" packagedb before running the test suite.

**Comment by DanielG** [comment]
> Sorry for bother with problems with a deprecated version, feel free to ignore this and to close the issue

No worries, I think this particular issue isn't specific to the fork anyways.

> So, weirdly enough, running ghc-pkg.exe list --simple-output Cabal inside the stack execution gives another value that running it directly or within cabal

Stack does some weird stuff with the GHC_PACKAGE_PATH environment variable so I'm not super surprised for ghc-pkg output to be different in a stack context.

What worries me is the:

```
Loaded package environment from D:\\msys64\tmp\stack2368\test-ghc-env
Loaded package environment from D:\\msys64\tmp\stack2368\test-ghc-env
```

messages. Since when does stack use ghc-environment files!?

The GHC commandline itself looks perfectly sane, no duplicate `-package Cabal` flags and `-hide-all-packages` is in effect.

```
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe
 -outputdir 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build'
 -o 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1'
 -optP-DCABAL_HELPER=1
 '-optP-DCH_MIN_VERSION_Cabal(major1,major2,minor)=(  (major1)  < 2 || (major1) == 2 && (major2)  < 4 || (major1) == 2 && (major2) == 4 && (minor) <= 0)'
 -i '-iC:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build'
 -hide-all-packages
 -package base
 -package containers
 -package directory
 -package filepath
 -package process
 -package bytestring
 -package ghc-prim
 -package Cabal-2.4.0.1
 -w
 --make 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Runtime\Main.hs'
```

So we must be dealing with some weird environment (variable) bullshit.

You can try running the ghc command manually in a terminal. If that works you'll have to print the environment ghc is getting somehow. On unix I would do that by making a wrapper script for GHC that runs `env` and then inject it by adjusting PATH I hope you know some way to do that on win32.

**Comment by jneira** [comment]
Well, maybe a quick check could be (in a msys console):
```
# stack exec env | grep -i GHC_PACKAGE_PATH
GHC_PACKAGE_PATH=D:\ws\haskell\haskell-ide-engine\.stack-work\install\69d95b10\pkgdb;D:\sr\snapshots\f64ff031\pkgdb;D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\lib\package.conf.d
```
so stack effectively is tweaking `GHC_PACKAGE_PATH` trying to avoid (some famous haskell build tool) hell :stuck_out_tongue: 

* Setting the env var with stack value manually and running the ghc invocation works as expected due to `-hide-all-packages`:
```
# export GHC_PACKAGE_PATH="D:\ws\haskell\haskell-ide-engine\.stack-work\install\69d95b10\pkgdb;D:\sr\snapshots\f64ff031\pkgdb;D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\lib\package.conf.d"
# "D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe" -outputdir 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -o 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1' -optP-DCABAL_HELPER=1 '-optP-DCH_MIN_VERSION_Cabal(major1,major2,minor)=(  (major1)  < 2 || (major1) == 2 && (major2)  < 4 || (major1) == 2 && (major2) == 4 && (minor) <= 0)' -i '-iC:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build' -hide-all-packages -package base -package containers -package directory -package filepath -package process -package bytestring -package ghc-prim -package Cabal-2.4.0.1 -w --make 'C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Runtime\Main.hs'
[1 of 4] Compiling CabalHelper.Shared.Common ( C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\Common.hs, C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\Common.o )
[2 of 4] Compiling CabalHelper.Shared.InterfaceTypes ( C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\InterfaceTypes.hs, C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\InterfaceTypes.o )
[3 of 4] Compiling CabalHelper.Shared.Sandbox ( C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\Sandbox.hs, C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Shared\Sandbox.o )
[4 of 4] Compiling Main             ( C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\CabalHelper\Runtime\Main.hs, C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1.build\Main.o )
Linking C:\Users\user\Local Settings\Cache\cabal-helper\cabal-helper0.9.0.0-Cabal2.4.0.1 ...
```
* Printing other env var set by stack i've found:
```
# stack exec env | grep -i GHC_ENVIRONMENT
GHC_ENVIRONMENT=-
```

* The contents of used `test-ghc-env` when running `stack test :dispatcher-test --keep-tmp-files` in `haskell-ide-engine`:

```
clear-package-db
global-package-db
package-db D:\sr\snapshots\f64ff031\pkgdb
package-db D:\ws\haskell\haskell-ide-engine\.stack-work\install\69d95b10\pkgdb
package-id haskell-ide-engine-0.12.0.0-71ofgOVvJxrD3H0yeqPY3F
package-id template-haskell-2.14.0.0
package-id Cabal-2.4.1.0-78x0vw3MyCl4xpT30nlxaF
.... more packages
```

wow, it seems the use of that ghc environment makes ghc ignore `-hide-all-packages` ??? :open_mouth: :worried: 

I am using lastest stable version of stack:
```
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

**Comment by jneira** [comment]
FYI, [applying the workaround](https://github.com/jneira/haskell-ide-engine/blob/azure-win-tests/.azure/linux-stack.yml#L81-L84) described [above ](https://github.com/DanielG/cabal-helper/issues/78#issuecomment-538378774) i've got the tests in azure not fail due to this issue: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=219
(the test suites are even passing for ghc-8.2.2 :smile:)

**Comment by jneira** [comment]
It seems `stack` are using ghc env files specifically for test executions: see https://github.com/commercialhaskell/stack/issues/4896#issuecomment-504661637 and https://github.com/commercialhaskell/stack/issues/4896
I dont like the workaround of unsetting `GHC_ENVIRONMENT` cause it would bother advanced users that want to use it but maybe it could be done if it is possible to detect that the compiling is inside a stack test execution. :worried:

**Comment by jneira** [comment]
It seems that this compilation error is present in stack-2.?.? (reproduced with 2.1.3, not present in 1.9.3). That is the cause of hie succesful builds in circleci.

**Comment by DanielG** [comment]
Ok, I have a reproducer. This seems to be a GHC bug.

The [GHC User Guide, in the Package Environments chapter](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#package-environments) says:

> If such a package environment is found, it is equivalent to passing these command line arguments to ghc:
```
-hide-all-packages
-clear-package-db
-global-package-db
-user-package-db
-package-db db.d/
-package-id id_1
-package-id id_2
...
-package-id id_n
```
> Note the implicit *-hide-all-packages* [...]

If I construct a package-environment `ghc-2.4.1.0.env` that includes `Cabal-2.4.1.0`, and then do:

```
$ GHC_ENVIRONMENT=$PWD/ghc-2.4.1.0.env ghc -hide-all-packages -package Cabal-2.2.0.1 Test.hs
Test.hs:1:1: error:
    Ambiguous module name ‘Distribution.Simple’:
      it was found in multiple packages: Cabal-2.2.0.1 Cabal-2.4.1.0
```

(This is with ghc-8.4.4 where Cabal-2.2.0.1 is a boot package for convinience)

This seems to contradict the documentation in that `-hide-all-packages` doesn't seem to be added again.

The same thing happens with:

    $ ghc -hide-all-packages -package Cabal-2.2.0.1 -package-env ./ghc-2.4.1.0.env Test.hs

So this is not specific to the GHC_ENVIRONMENT variable.

At this point I had a hunch, consider this command line:

     $ ghc -hide-all-packages -package base -package Cabal-2.2.0.1 -hide-all-packages -package base -package Cabal-2.4.1.0 Test.hs

Note the two `-hide-all-packages` flags. Now we might naively expect that the second one removes the first two `-package` flags from the active set but this does not seem to happen, it still fails with the same error as above!

**Comment by DanielG** [comment]
After some more brooding on this I'm not so sure it can really be considered a GHC bug. The package environment overriding explicit package dependencies given on the command line wouldn't give very sensible behaviour either.

What I still don't understand is how we're even ending up with two different versions of Cabal in a Stack project anyways.

Could you see what Cabal versions are floating around in the `.stack-work`/stack snapshot package-dbs? (`ghc-pkg --package-db=<path>` is your friend).

**Comment by jneira** [comment]
Yeah, maybe the `stack exec ghc-pkg -- --list Cabal` i posted above could be useful?

```
D:\ws\haskell\haskell-ide-engine>stack exec ghc-pkg -- list Cabal
D:\bin\Programs\stack\x86_64-windows\ghc-8.6.5\lib\package.conf.d
    Cabal-2.4.0.1

D:\sr\snapshots\f64ff031\pkgdb
    Cabal-2.4.1.0

D:\ws\haskell\haskell-ide-engine\.stack-work\install\69d95b10\pkgdb
    (no packages)
```

So it seems stack uses the global package db (with `Cabal.2.4.0.1`) and a user package db with the dependencies taken from `stack.yaml`. The project was built with [`resolver: lts-13.30`](https://www.stackage.org/lts-13.30) which has `Cabal-2.4.1.0`. 
Note that both specific stack package dbs and a `package-id Cabal-2.4.1.0-78x0vw3MyCl4xpT30nlxaF` are in the `test-ghc-env` file used within `stack test` (so is seems other subcommands would not have the problem?)

**Comment by DanielG** [comment]
I wasn't aware that stack(age) can get into this situation where the Cabal version shipped with GHC is different from the one that is in the stackage snapshot but apparently it can. See also commercialhaskell/stackage#4425.

Looking at stack's code, commercialhaskell/stack@f01253e472f08254d00b8ce666656f4fee80e507 introduced their use of `GHC_ENVIRONMENT` for tests, there is another related commit commercialhaskell/stack@7b392d155e58d8de26cd09a23b62ebac55b1ff79 which just always sets `GHC_ENVIRONMENT=-` to make GHC not look for v2-build's `.ghc.environment*` files but that bit isn't conflicting with our GHC compilation AFAICT.

The easiest solution for us I can see would be to just _always_ unset GHC_ENVIRONMENT and GHC_PACKAGE_PATH unconditionally. I think that's actually a fairly sound approach since we're only dealing with GHC boot packages when compiling the helper anyways so additional package dbs and environments are never relevant.

I don't really see a "proper" solution. IMO Stack's setting of `GHC_ENVIRONMENT` for tests is simply ill concived but since it's apparently needed by `doctest` a lot of people would probably object to it being removed again.

Let me expand on the "ill concived" part a bit: since Stack can be dealing with two different Cabal versions, namely the one that's in the stackage snapshot one and the one that shipped with the GHC bindist, there can never be a _single_ ghc environment that is fit for all situations. Some packages, like HIE, might want the GHC-boot Cabal version because of their dependency on the ghc library but others might legitimately need the newer version in the snapshot.

The only real way out of this mess would be to simply forbid Stackage snapshots from having diverging Cabal versions but from the issue linked above it seems they don't really want to do that, and besides we already have a snapshot with this breakage in the wild anyways.
