### ISSUE TITLE
cabal-helper error with a custom cabal `store-dir`

### ISSUE THREAD

**Issue by jneira** [DanielG/cabal-helper#83]
* when compiling at runtime cabal-helper creates a package environment included the path to the default `store-dir` (`C:\Users\user\AppData\Roaming\cabal\store\ghc-8.6.5\package.db`) in its ghc package environment in `C:\Users\user\Local Settings\Cache\cabal-helper\ghc-8.6.5.package-envs\Cabal-3.0.0.0.package-env`.
* if you change the value of `store-dir` in the glocal cabal config (to avoid max paths issues in windows f.e.) that location doesnt exists
* it causes the calls to cabal-helper fails with
```
Loaded package environment from C:\Users\user\Local Settings\Cache\cabal-helper\ghc-8.6.5.package-envs\Cabal-3.0.0.0.package-env
ghc.exe: can't find a package database at C:\Users\user\AppData\Roaming\cabal\store\ghc-8.6.5\package.db
```
* changing manually the path in `Cabal-3.0.0.0.package-env` to the actual one makes it work

**Comment by DanielG** [comment]
My guess is this is because of https://github.com/haskell/cabal/issues/5925

**Comment by jneira** [comment]
It seems so, i'll try to submit a patch upstream

**Comment by jneira** [comment]
I was trying to reproduce the bad path in the gch env file and i am not being able to do it with :

* `cabal-2.4.1.0 v2-build`
* `cabal build --write-ghc-environment-files=ghc8.4.4+` with `cabal-3.0.0.0`

Both of them generate a `.ghc.environment.x86_64-mingw32-8.6.5` file with the correct custom `store-dir` inside. (i've got them dowloading from the official cabal site :smile:)

**Comment by DanielG** [comment]
It's entirely possible that `v2-install --lib --package-env=FILE` behaves differently here and that's what cabal-helper is using to install Cabal, not v2-build.

**Comment by jneira** [comment]
@DanielG you are right, that precise command writes the bad one :open_mouth:

**Comment by jneira** [comment]
I've [opened a pr upstream](https://github.com/haskell/cabal/pull/6298) but we will have to wait to a new cabal release (if it is accepted). I wonder it it worths to try to workaround here in the meanwhile

**Comment by DanielG** [comment]
Can't you just use a symlink as a workaround on your end? Honestly upgrading cabal is usually quite painless because it has such a wide backwards compatibility window so I don't think it's worth it.

**Comment by jneira** [comment]
Yeah, it would be a general fix for the cabal code that still looks for the default store dir ignoring the global config file. Or simply editing the ghc env file once it is cached to workaround this concrete problem.
I was thinking in hie users that dont know (and dont care?) what hie uses internally and could get frustated by misterious errors when using it.
However not all users change the default store dir (although they should do it in windows!) and we can add a note in docs somewhere.
