### ISSUE TITLE
Consider replace temporary private lib with a common stanza to avoid cabal bug

### ISSUE THREAD

**Issue by jneira** [DanielG/cabal-helper#94]
* To avoid a infamous cabal bug with private libs: see https://github.com/haskell/cabal/issues/6483 duplicated of https://github.com/haskell/cabal/issues/6211
* Workarounds:
  * Using a separated `store-dir` for `cabal build` and `cabal v2-install` seems to avoid the issue
  * Wipe out the entire `store-dir` (ugh) or remove `cabal-plan` dirs from it and run `cabal-store-check --repair`
* @DanielG i could prepare a pr if you agree, including a TODO to restore the private lib when the bug is fixed

**Comment by DanielG** [comment]
Sure, I think I said on IRC already that I'd accept such a patch.

**Comment by jneira** [comment]
Would be this one closed by #97?

**Comment by DanielG** [comment]
Yup, closing.
